# Generated by Django 5.2 on 2025-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_barangay_city_country_remove_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
