# Generated by Django 5.0.2 on 2025-05-18 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_emailverificationtoken_alter_barangay_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='jobs_emailv_user_id_7d3757_idx',
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['user'], name='jobs_emailv_user_id_c96227_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['token_type'], name='jobs_emailv_token_t_c122c8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['expires_at'], name='jobs_emailv_expires_b1aa34_idx'),
        ),
    ]
