# Generated by Django 5.2.1 on 2025-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_company_name_alter_job_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional information you would like to share with the employer', null=True),
        ),
    ]
