# Generated by Django 5.2.1 on 2025-05-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobapplication_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for job inquiries', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number for job inquiries', max_length=20, null=True),
        ),
    ]
