services:
  - type: web
    name: jobpoint
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn jobpoint.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: jobpoint-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: "False"
      - key: STATIC_ROOT
        value: staticfiles
      - key: STATIC_URL
        value: /static/

databases:
  - name: jobpoint-db
    databaseName: jobpoint
    user: jobpoint 